export const usersData = [
  {
    id: 1,
    first_name: "Kristine",
    last_name: "Winkless",
    email: "kwinkless0@feedburner.com",
    gender: "Agender",
  },
  {
    id: 2,
    first_name: "Kaleb",
    last_name: "Tuppeny",
    email: "ktuppeny1@fema.gov",
    gender: "Agender",
  },
  {
    id: 3,
    first_name: "Ronnie",
    last_name: "Gorsse",
    email: "rgorsse2@wisc.edu",
    gender: "Bigender",
  },
  {
    id: 4,
    first_name: "Susanna",
    last_name: "Braywood",
    email: "sbraywood3@printfriendly.com",
    gender: "Male",
  },
  {
    id: 5,
    first_name: "Francesca",
    last_name: "Vigne",
    email: "fvigne4@paypal.com",
    gender: "Genderfluid",
  },
  {
    id: 6,
    first_name: "Persis",
    last_name: "Ellicock",
    email: "pellicock5@ihg.com",
    gender: "Bigender",
  },
  {
    id: 7,
    first_name: "Rhiamon",
    last_name: "O'Connolly",
    email: "roconnolly6@acquirethisname.com",
    gender: "Bigender",
  },
  {
    id: 8,
    first_name: "Evelyn",
    last_name: "Dowber",
    email: "edowber7@bizjournals.com",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Erminia",
    last_name: "Van Weedenburg",
    email: "evanweedenburg8@loc.gov",
    gender: "Genderqueer",
  },
  {
    id: 10,
    first_name: "Shawna",
    last_name: "Forsdyke",
    email: "sforsdyke9@skyrock.com",
    gender: "Polygender",
  },
];
